#syntax=ghcr.io/aica-technology/package-builder:v1.4.0

[metadata]
version = "0.0.1"
## add a description of the AICA package
# description = "My custom package"

[build]
type = "ros"
image = "v2.0.4-jazzy"

[build.dependencies]
"@aica/foss/control-libraries" = "v9.1.0"
"@aica/foss/modulo" = "v5.2.0"

[build.packages.my-custom-package]
source = "./source/my_custom_package"

## add any required apt dependencies for the custom package.
## these packages will be available during the build but also in the final image,
## so they are useful for dynamic libraries
#[build.packages.my-custom-package.dependencies.apt]
#ros-jazzy-cv-detection = "*"
