schema: 2-0-4
dependencies:
  core: v4.2.0
frames:
  base:
    reference_frame: world
    position:
      x: 0.44
      y: 0
      z: 0.19
    orientation:
      w: 0
      x: 0.707
      y: -0.707
      z: 0
  reposition_1:
    reference_frame: world
    position:
      x: 0.461514
      y: -0.235
      z: 0.4
    orientation:
      w: 0
      x: -0.707107
      y: 0.707107
      z: 0
  repositionnement:
    reference_frame: world
    position:
      x: 0.461468
      y: -0.12
      z: 0.4
    orientation:
      w: 0
      x: -0.707107
      y: 0.707107
      z: 0
  reposition_2:
    reference_frame: world
    position:
      x: 0.35
      y: -0.16
      z: 0.4
    orientation:
      w: 0
      x: -0.707107
      y: 0.707107
      z: 0
  reposition_3:
    reference_frame: world
    position:
      x: 0.35
      y: -0.258
      z: 0.4
    orientation:
      w: 0
      x: -0.707107
      y: 0.707107
      z: 0
  reposition_4:
    reference_frame: world
    position:
      x: 0.386081
      y: -0.258
      z: 0.4
    orientation:
      w: 0
      x: -0.707107
      y: 0.707107
      z: 0
  inter:
    reference_frame: world
    position:
      x: 0.28
      y: 0.15
      z: 0.1
    orientation:
      w: 0
      x: -1
      y: 0
      z: 0
  gravure:
    reference_frame: world
    position:
      x: 0.2115
      y: 0.364
      z: 0.1
    orientation:
      w: 0
      x: -1
      y: 0
      z: 0
  global_box:
    reference_frame: world
    position:
      x: 0.52
      y: 0.045
      z: 0.3
    orientation:
      w: 1
      x: 0
      y: 0
      z: 0
  reposition_5:
    reference_frame: world
    position:
      x: 0.461514
      y: -0.12
      z: 0.4
    orientation:
      w: 0.705204
      x: 0.051846
      y: -0.051846
      z: 0.705204
  reposition_6:
    reference_frame: world
    position:
      x: 0.461514
      y: -0.2
      z: 0.4
    orientation:
      w: 0.70709
      x: 0.004869
      y: -0.004869
      z: 0.70709
on_start:
  load:
    - component: box_collider_2
    - component: frame_to_signal
    - component: realsense_camera
    - component: frame_to_signal_copy
    - hardware: hardware
    - component: piece_detection
    - component: creality_interface
    - component: box_collider
sequences:
  sequence:
    display_name: Sequence
    steps:
      - delay: 1
      - switch_controllers:
          hardware: hardware
          activate: joint_trajectory_controller
      - delay: 0.25
      - call_service:
          controller: joint_trajectory_controller
          hardware: hardware
          service: set_trajectory
          payload: "{frames: [base, repositionnement, reposition_1, repositionnement,
            reposition_5, reposition_6, reposition_5, repositionnement,
            reposition_2, reposition_3, reposition_4, reposition_3,
            reposition_2, base, inter, gravure], times_from_start: [0.5, 1.5,
            2.5, 3, 5, 6, 6.5, 8.5, 9, 9.5, 10.5, 11, 11.5, 12.5, 14, 15]}"
      - check:
          condition:
            controller: joint_trajectory_controller
            hardware: hardware
            predicate: has_trajectory_succeeded
          wait_forever: true
      - call_service:
          component: creality_interface
          service: run_gcode
          payload: /gcodes/dxf3.dxf
      - check:
          condition:
            component: creality_interface
            predicate: laser_finished
          wait_forever: true
      - call_service:
          controller: joint_trajectory_controller
          hardware: hardware
          service: set_trajectory
          payload: "{frames: [inter, base], times_from_start: [1,2.5]}"
      - check:
          condition:
            controller: joint_trajectory_controller
            hardware: hardware
            predicate: has_trajectory_succeeded
          wait_forever: true
      - set:
          parameter: command
          value: !!float 200.0
          hardware: hardware
          controller: gpio_controller
      - switch_controllers:
          hardware: hardware
          deactivate: joint_trajectory_controller
      - delay: 1
      - switch_controllers:
          hardware: hardware
          activate: ik_velocity_controller
components:
  realsense_camera:
    component: realsense2_camera::RealSenseNodeFactory
    display_name: RealSense Camera
    parameters:
      enable_accel: false
      enable_confidence: false
      enable_depth: true
      enable_gyro: false
      enable_infra: false
      align_depth_enable: true
      rgb_camera_profile: 1280x720x30
      depth_module_profile: 1280x720x30
      spatial_filter_enable: true
      temporal_filter_enable: true
    outputs:
      aligned_depth_to_color_image_raw: /realsense_camera/aligned_depth_to_color_image_raw
      aligned_depth_to_color_camera_info: /realsense_camera/aligned_depth_to_color_camera_info
      color_image_raw: /realsense_camera/color_image_raw
  piece_detection:
    component: my_custom_package::PieceDetection
    display_name: Piece Detection
    events:
      transitions:
        on_load:
          lifecycle:
            component: piece_detection
            transition: configure
        on_configure:
          lifecycle:
            component: piece_detection
            transition: activate
      predicates:
        is_piece_not_confirmed:
          load:
            component: signal_point_attractor_copy
          unload:
            component: signal_point_attractor
        is_piece_confirmed:
          load:
            component: signal_point_attractor
          unload:
            component: signal_point_attractor_copy
    parameters:
      rate: !!float 50.0
      piece_path: /meshes/piece.stl
      number_of_points: 4000
      voxel_size: 0.002
      camera_pose_world:
        - 0.420451
        - 0.0175
        - 0.766251
        - !!float 0.0
        - 0.707107
        - -0.707107
        - !!float 0.0
    inputs:
      depth_image: /realsense_camera/aligned_depth_to_color_image_raw
      depth_camera_info: /realsense_camera/aligned_depth_to_color_camera_info
      color_image: /realsense_camera/color_image_raw
    outputs:
      piece_pose: /piece_detection/piece_pose
  signal_point_attractor:
    component: aica_core_components::motion::SignalPointAttractor
    display_name: Signal Point Attractor
    events:
      transitions:
        on_load:
          lifecycle:
            component: signal_point_attractor
            transition: configure
        on_configure:
          lifecycle:
            component: signal_point_attractor
            transition: activate
    parameters:
      max_linear_velocity: 0.2
      max_angular_velocity: 0.2
    inputs:
      state: /hardware/robot_state_broadcaster/cartesian_state
      attractor: /piece_detection/piece_pose
    outputs:
      twist: /signal_point_attractor/twist
  box_collider:
    component: aica_core_components::utility::BoxCollider
    display_name: Box Collider prise pièce
    events:
      predicates:
        is_in_bounds:
          unload:
            component: signal_point_attractor
          switch_controllers:
            hardware: hardware
            deactivate: ik_velocity_controller
          set:
            parameter: command
            value: !!float -10.0
            hardware: hardware
            controller: gpio_controller
          sequence:
            start: sequence
      transitions:
        on_load:
          lifecycle:
            component: box_collider
            transition: configure
        on_configure:
          lifecycle:
            component: box_collider
            transition: activate
    parameters:
      publish_marker: true
      x_size: 0.01
      y_size: 0.02
      z_size: 0.025
    inputs:
      target: /hardware/robot_state_broadcaster/cartesian_state
      center: /piece_detection/piece_pose
  creality_interface:
    component: my_custom_package::CrealityInterface
    display_name: Creality Interface
    parameters:
      usb_path: /dev/ttyACM0
  box_collider_2:
    component: aica_core_components::utility::BoxCollider
    display_name: Box Collider global box
    events:
      transitions:
        on_load:
          lifecycle:
            component: box_collider_2
            transition: configure
        on_configure:
          lifecycle:
            component: box_collider_2
            transition: activate
    parameters:
      publish_marker: true
      x_size: 0.3
      y_size: 0.4
      z_size: 0.55
    inputs:
      target: /piece_detection/piece_pose
      center: /frame_to_signal/pose
  frame_to_signal:
    component: aica_core_components::ros::TfToSignal
    display_name: Frame to Signal global_box
    events:
      transitions:
        on_load:
          lifecycle:
            component: frame_to_signal
            transition: configure
        on_configure:
          lifecycle:
            component: frame_to_signal
            transition: activate
    parameters:
      frame: global_box
    outputs:
      pose: /frame_to_signal/pose
  signal_point_attractor_copy:
    component: aica_core_components::motion::SignalPointAttractor
    display_name: Signal Point Attractor copy
    events:
      transitions:
        on_load:
          lifecycle:
            component: signal_point_attractor_copy
            transition: configure
        on_configure:
          lifecycle:
            component: signal_point_attractor_copy
            transition: activate
    parameters:
      max_linear_velocity: 0.2
      max_angular_velocity: 0.2
    inputs:
      state: /hardware/robot_state_broadcaster/cartesian_state
      attractor: /frame_to_signal_copy/pose
    outputs:
      twist: /signal_point_attractor/twist
  frame_to_signal_copy:
    component: aica_core_components::ros::TfToSignal
    display_name: Frame to Signal base
    events:
      transitions:
        on_load:
          lifecycle:
            component: frame_to_signal_copy
            transition: configure
        on_configure:
          lifecycle:
            component: frame_to_signal_copy
            transition: activate
    parameters:
      frame: base
    outputs:
      pose: /frame_to_signal_copy/pose
hardware:
  hardware:
    display_name: Hardware Interface
    urdf: ufactory_with_table
    rate: 100
    events:
      transitions:
        on_load:
          load:
            - controller: robot_state_broadcaster
              hardware: hardware
            - controller: gpio_controller
              hardware: hardware
            - controller: ik_velocity_controller
              hardware: hardware
            - controller: joint_trajectory_controller
              hardware: hardware
    controllers:
      robot_state_broadcaster:
        plugin: aica_core_controllers/RobotStateBroadcaster
        outputs:
          cartesian_state: /hardware/robot_state_broadcaster/cartesian_state
        events:
          transitions:
            on_load:
              switch_controllers:
                hardware: hardware
                activate: robot_state_broadcaster
      gpio_controller:
        plugin: aica_core_controllers/gpio/GPIOController
        parameters:
          gpio: gripper
          command_interface: position
          command: !!float 200.0
        events:
          transitions:
            on_load:
              switch_controllers:
                hardware: hardware
                activate: gpio_controller
      ik_velocity_controller:
        plugin: aica_core_controllers/velocity/IKVelocityController
        inputs:
          command: /signal_point_attractor/twist
        events:
          transitions:
            on_load:
              switch_controllers:
                hardware: hardware
                activate: ik_velocity_controller
      joint_trajectory_controller:
        plugin: aica_core_controllers/trajectory/JointTrajectoryController
graph:
  positions:
    on_start:
      x: -680
      y: -20
    stop:
      x: -680
      y: 80
    buttons:
      button:
        x: -340
        y: -400
      button_2:
        x: 3780
        y: 1360
    components:
      realsense_camera:
        x: 100
        y: 200
      piece_detection:
        x: 620
        y: 40
      signal_point_attractor:
        x: 3280
        y: 60
      box_collider:
        x: 1320
        y: 360
      creality_interface:
        x: 4340
        y: 940
      box_collider_2:
        x: 620
        y: 600
      frame_to_signal:
        x: 120
        y: 680
      signal_point_attractor_copy:
        x: 3280
        y: -360
      frame_to_signal_copy:
        x: 2820
        y: -280
    hardware:
      hardware:
        x: 4560
        y: -1040
    sequences:
      sequence:
        x: 1760
        y: 640
  buttons:
    button: {}
    button_2:
      on_click:
        call_service:
          component: creality_interface
          service: run_gcode
          payload: /gcodes/dxf3.dxf
  edges:
    hardware_hardware_joint_trajectory_controller_has_trajectory_succeeded_hardware_hardware_gpio_controller:
      path:
        - x: 580
          y: -460
        - x: 580
          y: -280
    hardware_hardware_joint_trajectory_controller_has_trajectory_succeeded_sequence_sequence_condition_input_4:
      path:
        - x: 3600
          y: 180
        - x: 3600
          y: 940
        - x: 2940
          y: 940
    creality_interface_is_finished_sequence_sequence_condition_input_6:
      path:
        - x: 4280
          y: 1020
        - x: 4280
          y: 1200
        - x: 3300
          y: 1200
    creality_interface_laser_finished_sequence_sequence_condition_input_6:
      path:
        - x: 4280
          y: 1060
        - x: 4280
          y: 1280
        - x: 3300
          y: 1280
    hardware_hardware_joint_trajectory_controller_has_trajectory_succeeded_sequence_sequence_condition_input_9:
      path:
        - x: 4180
          y: 120
        - x: 4180
          y: 1120
        - x: 3400
          y: 1120
    piece_detection_is_piece_confirmed_condition_condition_all0_0:
      path:
        - x: 1340
          y: 260
        - x: 1340
          y: -80
    on_start_on_start_box_collider_2_box_collider_2:
      path:
        - x: -520
          y: 20
        - x: -520
          y: 660
    on_start_on_start_frame_to_signal_frame_to_signal:
      path:
        - x: -520
          y: 20
        - x: -520
          y: 740
    on_start_on_start_realsense_camera_realsense_camera:
      path:
        - x: -520
          y: 20
        - x: -520
          y: 260
    on_start_on_start_frame_to_signal_copy_frame_to_signal_copy:
      path:
        - x: 1300
          y: 20
        - x: 1300
          y: -220
    on_start_on_start_hardware_hardware:
      path:
        - x: 420
          y: 20
        - x: 420
          y: -980
    on_start_on_start_piece_detection_piece_detection:
      path:
        - x: -520
          y: 20
        - x: -520
          y: 100
    on_start_on_start_creality_interface_creality_interface:
      path:
        - x: -520
          y: 20
        - x: -520
          y: 980
        - x: 1240
          y: 980
        - x: 1240
          y: 1280
        - x: 4300
          y: 1280
        - x: 4300
          y: 1000
    on_start_on_start_box_collider_box_collider:
      path:
        - x: 1300
          y: 20
        - x: 1300
          y: 420
    button_2_on_click_creality_interface_run_gcode:
      path:
        - x: 4220
          y: 1380
        - x: 4220
          y: 1200
    piece_detection_is_piece_not_confirmed_signal_point_attractor_copy_signal_point_attractor_copy:
      path:
        - x: 1080
          y: 300
        - x: 1080
          y: -300
    piece_detection_is_piece_not_confirmed_signal_point_attractor_signal_point_attractor:
      path:
        - x: 1180
          y: 300
        - x: 1180
          y: 120
    piece_detection_is_piece_confirmed_signal_point_attractor_signal_point_attractor:
      path:
        - x: 1180
          y: 260
        - x: 1180
          y: 120
    piece_detection_is_piece_confirmed_signal_point_attractor_copy_signal_point_attractor_copy:
      path:
        - x: 1080
          y: 260
        - x: 1080
          y: -300
    box_collider_is_in_bounds_signal_point_attractor_signal_point_attractor:
      path:
        - x: 3240
          y: 580
        - x: 3240
          y: 120
    box_collider_is_in_bounds_hardware_hardware_ik_velocity_controller:
      path:
        - x: 3980
          y: 580
        - x: 3980
          y: -260
    box_collider_is_in_bounds_hardware_hardware_gpio_controller:
      path:
        - x: 3780
          y: 580
        - x: 3780
          y: -400
    piece_detection_piece_pose_signal_point_attractor_attractor:
      path:
        - x: 2140
          y: 380
        - x: 2140
          y: 360
    piece_detection_piece_pose_box_collider_center:
      path:
        - x: 1180
          y: 380
        - x: 1180
          y: 700
    piece_detection_piece_pose_box_collider_2_target:
      path:
        - x: 1080
          y: 380
        - x: 1080
          y: 520
        - x: 580
          y: 520
        - x: 580
          y: 860
    hardware_hardware_robot_state_broadcaster_cartesian_state_signal_point_attractor_state:
      path:
        - x: 1240
          y: -500
        - x: 1240
          y: 320
    hardware_hardware_robot_state_broadcaster_cartesian_state_box_collider_target:
      path:
        - x: 1240
          y: -500
        - x: 1240
          y: 660
    hardware_hardware_robot_state_broadcaster_cartesian_state_signal_point_attractor_copy_state:
      path:
        - x: 3240
          y: -500
        - x: 3240
          y: -100
    signal_point_attractor_twist_hardware_hardware_ik_velocity_controller_command:
      path:
        - x: 3700
          y: 320
        - x: 3700
          y: -100
    sequence_sequence_event_trigger_1_hardware_hardware_joint_trajectory_controller:
      path:
        - x: 1960
          y: 1240
        - x: 4140
          y: 1240
        - x: 4140
          y: -40
    sequence_sequence_event_trigger_3_hardware_hardware_joint_trajectory_controller_set_trajectory:
      path:
        - x: 2280
          y: 1160
        - x: 4220
          y: 1160
        - x: 4220
          y: 200
    hardware_joint_trajectory_controller_has_trajectory_succeeded_condition_sequence_sequence_condition_input_4:
      path:
        - x: 4180
          y: 120
        - x: 4180
          y: 1120
        - x: 2440
          y: 1120
    sequence_sequence_event_trigger_5_creality_interface_run_gcode:
      path:
        - x: 2600
          y: 1200
    creality_interface_laser_finished_condition_sequence_sequence_condition_input_6:
      path:
        - x: 4740
          y: 1120
        - x: 4740
          y: 960
        - x: 4260
          y: 960
        - x: 4260
          y: 1080
        - x: 2760
          y: 1080
    sequence_sequence_event_trigger_10_hardware_hardware_joint_trajectory_controller:
      path:
        - x: 3400
          y: 1040
        - x: 4140
          y: 1040
        - x: 4140
          y: -40
    box_collider_is_in_bounds_sequence_sequence:
      path:
        - x: 1740
          y: 580
        - x: 1740
          y: 700
    sequence_sequence_event_trigger_7_hardware_hardware_joint_trajectory_controller_set_trajectory:
      path:
        - x: 2920
          y: 1160
        - x: 4220
          y: 1160
        - x: 4220
          y: 200
    hardware_joint_trajectory_controller_has_trajectory_succeeded_condition_sequence_sequence_condition_input_8:
      path:
        - x: 4180
          y: 120
        - x: 4180
          y: 960
        - x: 3080
          y: 960
    sequence_sequence_event_trigger_9_hardware_hardware_gpio_controller:
      path:
        - x: 3240
          y: 1000
        - x: 4100
          y: 1000
        - x: 4100
          y: -400
    sequence_sequence_event_trigger_12_hardware_hardware_ik_velocity_controller:
      path:
        - x: 3720
          y: 920
        - x: 4280
          y: 920
        - x: 4280
          y: -260
